#!/bin/sh

num=$1
diffic=$2
problem=$(echo "$3" | sed 's|https://leetcode.com/problems/||' | sed 's|/$||')
echo "Setting up: $problem"

ndir='1000-beyond'
if [ $num -lt 1000 ]; then
  ndir='100-999'
  if [ $num -lt 100 ]; then
    ndir='1-99';
  fi
fi
pdir="src/leetcode/$ndir/$num-$diffic-$problem"

mkdir $pdir
echo "From https://leetcode.com/problems/$problem/" > $pdir/README.md
git add $pdir/README.md

echo "module.exports=TBD;" > $pdir/$problem.js
git add $pdir/$problem.js

echo "const TBD = require('./$problem');" > $pdir/$problem.test.js
git add $pdir/$problem.test.js
